services:
  - type: web
    name: mosaic-orcamentos-api
    runtime: go
    rootDir: backend
    buildCommand: go build -tags netgo -ldflags "-s -w" -o app .
    startCommand: ./app
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
